#!/bin/bash
# Software License Agreement (BSD)
#
# Author    Mike Purvis <mpurvis@clearpathrobotics.com>
# Copyright (c) 2014-2016, Clearpath Robotics, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that
# the following conditions are met:
# * Redistributions of source code must retain the above copyright notice, this list of conditions and the
#   following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
#   following disclaimer in the documentation and/or other materials provided with the distribution.
# * Neither the name of Clearpath Robotics nor the names of its contributors may be used to endorse or
#   promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

ROS_DISTRO=${ROS_DISTRO:-melodic}
ROS_CONFIGURATION=${ROS_CONFIGURATION:-desktop_full}
ROS_EXTRA_PACKAGES=${ROS_EXTRA_PACKAGES:-}
ROS_INSTALL_DIR=${ROS_INSTALL_DIR:-/opt/ros/${ROS_DISTRO}}

do_install()
{

  # Rosdep has an issue detecting that qt5 is correctly installed, so preinstall it. This is a keg-only formula,
  # so add its location to the prefix path in order for workspace packages to be able to find it.
  export CMAKE_PREFIX_PATH=$(brew --prefix qt5)

  # This hack is required to make qt_gui_cpp compile correctly. See https://github.com/mikepurvis/ros-install-osx/pull/84#issuecomment-338209466
  export PATH="/usr/local/opt/qt5/bin:$PATH"
  pushd /usr/local/share/sip
  if [ ! -e PyQt5 ]; then
    ln -fvs Qt5 PyQt5
  fi
  popd

  # get openssl and gpgme working for rosbag_storage
  brew install openssl
  export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/openssl/lib/pkgconfig"

  # Mock out python and pip so that we get the brewed versions when rosdep and other programs call them.
  # Mock out pip so that we get the brewed pip2 when rosdep calls it to make an installation.
  export PATH=$(pwd)/shim:$PATH

  # Initialize and update rosdep
  if [ ! -d /etc/ros/rosdep/ ]; then
    echo "This sudo prompt is to initialize rosdep (creates the /etc/ros/rosdep path)."
    sudo rosdep init
  fi
  if [ ! -f /etc/ros/rosdep/sources.list.d/10-ros-install-osx.list ]; then
    echo "This sudo prompt adds the the brewed python rosdep yaml to /etc/ros/rosdep/sources.list.d/10-ros-install-osx.list"
    sudo sh -c "echo 'yaml file://$(pwd)/rosdeps.yaml osx' > /etc/ros/rosdep/sources.list.d/10-ros-install-osx.list"
  fi
  rosdep update

  # Remove previous workspace if present, create and enter new one.
  WS=${ROS_DISTRO}_${ROS_CONFIGURATION}_ws
  cd $WS

  # Standard source install

  # install specific versions of certain brew packages

  # sip 4.19.8_12 - still supports python2
  brew unlink sip
  brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/6d2b011fa8f28ef5a0b52f24eb687276823a22fa/Formula/sip.rb
  brew link sip

  # pyqt 5.10.1_1 - still supports python2
  brew unlink pyqt
  brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/1f389d65e21ad067be6811900f5361301b44839f/Formula/pyqt.rb
  brew link pyqt


  # patches
  echo "Applying patches"
  pwd

  # fix roscpp trying to link against unused? boost component
  #patch -N -d src/ros_comm/roscpp/ < ../patches/roscpp.diff

  # fix tf2 trying to link against unused? boost component
  patch -N -d src/geometry2/tf2/ < ../patches/tf2.patch

  # rosbag_strorage encryption
  patch -N -d src/ros_comm/rosbag_storage/ < ../patches/rosbag_storage.patch
  if [ ! -d /usr/local/include/openssl ]; then
    ln -s /usr/local/opt/openssl/include/* /usr/local/include/
  fi

  # fix boost components in camera_calibration_parsers
  patch -N -d src/image_common/camera_calibration_parsers/ < ../patches/camera_calibration_parsers.patch

  # fix boost components in camera_calibration_parsers
  patch -N -d src/vision_opencv/cv_bridge/ < ../patches/cv_bridge.patch

  # add pango to image_view
  patch -N -d src/image_pipeline/image_view/ < ../patches/image_view.patch

  # fix find flann library in pcl so pcl_ros can build
  # (https://stackoverflow.com/questions/53776238/building-point-cloud-library-pcl-on-macos-x-mojave-error-ld-library-not-foun)
  #patch -N -d /usr/local/share/pcl-1.9/Modules/ < ../patches/FindFLANN.diff

  # Clean out or create the install directory.
  if [ -d ${ROS_INSTALL_DIR} ]; then
    rm -rf ${ROS_INSTALL_DIR}/*
  else
    echo "This sudo prompt is to create and chown ${ROS_INSTALL_DIR}."
    sudo mkdir -p ${ROS_INSTALL_DIR}
    sudo chown $USER ${ROS_INSTALL_DIR}
    sudo chown $USER ${ROS_INSTALL_DIR}/../
  fi

  # Parallel build.
  catkin config --install \
    --install-space ${ROS_INSTALL_DIR} \
    --cmake-args \
      -DCMAKE_CXX_STANDARD=14 \
      -DCATKIN_ENABLE_TESTING=0 \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_FIND_FRAMEWORK=LAST \
      -DPYTHON_EXECUTABLE=$(which python2) \
      -DPYTHON_LIBRARY=$(python2 -c "import sys; print sys.prefix")/lib/libpython2.7.dylib \
      -DPYTHON_INCLUDE_DIR=$(python2 -c "import sys; print sys.prefix")/include/python2.7 \
      -DBoost_NO_BOOST_CMAKE=ON
#      -DCMAKE_MACOSX_RPATH=ON 
  catkin build

  echo "Installation successful, please source the ROS workspace:"
  echo
  echo "  source ${ROS_INSTALL_DIR}/setup.bash"
  echo
  
  # Check for SIP if on OSX/macOS 10.11 (El Capitan) or later
  if [[ `sw_vers -productVersion` > "10.10" ]]
  then
    if `csrutil status | grep -q enabled`
    then
      echo "You have System Integrity Protection enabled."
      echo
      echo "This prevents DYLD_LIBRARY_PATH from being exported to subshells"
      echo "Please add: export DYLD_LIBRARY_PATH=\$DYLD_LIBRARY_PATH:/opt/ros/\$ROS_DISTRO/lib"
      echo "To the start of /opt/ros/$ROS_DISTRO/bin/rosrun to work around the issue."
    fi
  fi
}

do_install
